version: '3.8'

services:
 campspot-checker:
  image: fredcorn/campspot-checker:latest
  build:
   context: .
  ports:
   - 49160:8787
  environment:
   - PORT=8787
  volumes:
   - ./:/app
   - /app/node_modules