version: '3.8'

services:
 campspot-checker:
  image: fredcorn/campspot-checker:latest
  build:
   context: .
  ports:
   - 49160:8080
  environment:
   - SERVER_PORT=8000
  volumes:
   - ./:/app
   - /app/node_modules
  command: node server.mjs