version: '3.8'

services:
 campspot-checker:
  platform: linux/amd64
  image: fredcorn/campspot-checker:amd64-latest
  build:
   context: .
  ports:
   - 49160:8080
  environment:
   - SERVER_PORT=8000
  volumes:
   - ./:/app
   - /app/node_modules